spring:
  application:
    name: auth-service
  cloud:
    stream:
      bindings:
        sendLoginEvent-out-0:
          destination: send-email
          group: ${spring.application.name}
      kafka:
        binder:
          brokers:
            - localhost:9092

    


  datasource:
    url: jdbc:postgresql://localhost:5432/library_auth_db
    username: admin
    password: admin
    driver-class-name: org.postgresql.Driver

  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.yaml

  jpa:
    hibernate:
      ddl-auto: validate

jwt:
  secret: mySuperSecretKeyThatIsAtLeast32CharactersLong
  expiration:
    time-minutes: 4

logging:
  level:
    org:
      springframework:
        security: DEBUG
        security.web: DEBUG

server:
  port: 8081
