spring:
  config:
    activate:
      on-profile: k8s

  cloud:
    consul:
      discovery:
        instance-id: ${HOSTNAME}:${server.port}
        service-name: auth-service
        health-check-url: http://auth-service:8081/actuator/health
        prefer-ip-address: false
