server:
  port: 9010

spring:
  cloud:
    function:
      definition: receiveLoginEvent
    stream:
      bindings:
        receiveLoginEvent-in-0:
          destination: send-email
          group: ${spring.application.name}
      kafka:
        binder:
          brokers:
            - localhost:9092

management:
  endpoints:
    web:
      exposure:
        include: health,info
