server:
  port: 9010

spring:
  cloud:
    function:
      definition: email
    stream:
      bindings:
        email-in-0:
          destination: send-email
          group: ${spring.application.name}
      kafka:
        binder:
          brokers:
            - localhost:9092

management:
  endpoints:
    web:
      exposure:
        include: health, metrics, prometheus
  endpoint:
    health:
      show-details: always
    metrics:
      enabled: true
    prometheus:
      enabled: true
