server:
  port: 9010

spring:
  cloud:
    stream:
      kafka:
        binder:
          brokers:
            - localhost:9092

management:
  endpoints:
    web:
      exposure:
        include: health,info
